CREATE TABLE MEMBER (
	USER_NO INT AUTO_INCREMENT,
	USER_ID VARCHAR(100) NOT NULL,
	USER_PW VARCHAR(1000) NOT NULL,
	USER_NAME VARCHAR(100) NOT NULL,
	AUTH VARCHAR(50) NOT NULL DEFAULT 'ROLE_USER',
	ENABLED tinyint(1) unsigned zerofill DEFAULT '1',
	PRIMARY KEY (USER_NO)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8
SELECT * FROM MEMBER;
-- unsigned는 양수만 허용되게 함 zerofill은 자릿수가 2자리면 1일경우 01이 채워짐

DELETE FROM MEMBER WHERE USER_ID='DD';
INSERT INTO MEMBER(USER_ID, USER_PW, USER_NAME) VALUES('DD','ASD','위영석');

CREATE TABLE BOARD (
	BOARD_NO INT AUTO_INCREMENT,
	BOARD_WRITER VARCHAR(100) NOT NULL,
	BOARD_TITLE VARCHAR(1000) NOT NULL,
	BOARD_CONTENT VARCHAR(2000) NOT NULL,
	REGDATE DATE NOT NULL,
	PRIMARY KEY
);