DROP SEQUENCE MYNOSEQ;
DROP TABLE MYBOARD;

CREATE SEQUENCE MYNOSEQ;

CREATE TABLE MYBOARD(
	MYNO NUMBER PRIMARY KEY,
	MYNAME VARCHAR2(500) NOT NULL,
	MYTITLE VARCHAR2(1000) NOT NULL,
	MYCONTENT VARCHAR2(2000) NOT NULL,
	MYDATE DATE NOT NULL
);
INSERT INTO MYBOARD
VALUES(MYNOSEQ.NEXTVAL, #{}, #{}, #{}, SYSDATE);

INSERT INTO MYBOARD
VALUES(MYNOSEQ.NEXTVAL, '위영석', 'ㅎㅇ', '안녕하세영', SYSDATE);
INSERT INTO MYBOARD
VALUES(MYNOSEQ.NEXTVAL, '성수민', 'ㅎㅇ2', '안녕하세영2', SYSDATE);

SELECT MYNO, MYNAME, MYTITLE, MYCONTENT, MYDATE
FROM MYBOARD
ORDER BY MYNO DESC;